// UPLOAD TO GITHUB ---DONE

// HOC TO LOAD DATA UNDER THE HOOD ---DONE

/***
  ---------------------------------------------------------------
***/

// ADD LOAD ONE ENTITY FUNCTION

// ADD CUSTOM HANDLING LOGIC IN ENTITIES REDUCER

// HANDLE INITIALLIZATION ERROR & GENERAL ERROR HANDLING 

// INSTALLATION PROCCES

// UPLOAD TO NPM

// CREATE EXAMPLES - ATTACH TO SAGAS REAL WORLD EXAMPLE

// CREATE FOR REDUX