// UPLOAD TO GITHUB ---DONE


// HOC TO LOAD DATA UNDER THE HOOD

// ADD CUSTOM HANDLING LOGIC IN ENTITIES REDUCER

// ADD LOAD ONE ENTITY FUNCTION

// HANDLE INITIALLIZATION ERROR & GENERAL ERROR HANDLING 

// INSTALLATION PROCCES

// UPLOAD TO NPM

// CREATE EXAMPLES - ATTACH TO SAGAS REAL WORLD EXAMPLE

// CREATE FOR REDUX